#!/usr/bin/env python3
"""A requirement change reports the chapters and test suites it lands on (T-0107, TS-18).

A pull request that edits `Requirements/` moves ground under the architecture chapter and the test
family that implement it. This reads the diff, collects the requirement ids it touches, resolves
each through the `## Traceability` table of its own family file, and prints the markdown a workflow
posts on the pull request. Ranges, id expansion and family splitting are reused from
`verify-traceability.py` rather than parsed a second time.

    report-pr-impact.py --diff-file <path> [docs-root]     # a unified diff, or - for stdin
    report-pr-impact.py --base origin/main [docs-root]     # diff against a git ref
    report-pr-impact.py --selftest
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys
import tempfile
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("verify_traceability", _HERE / "verify-traceability.py")
_trace = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_trace)

DIFF_FILE = re.compile(r"^\+\+\+ b/(.+)$")
DIFF_LINE = re.compile(r"^([+-])(?!\+\+|--)(.*)$")
# a change to one of these families is a change to an access-control or cryptographic invariant
SENSITIVE = {"R", "GW", "PW", "I", "AG", "SP", "PF", "OPS", "DS"}


def changed_ids(diff: str) -> dict[str, set[str]]:
    """{'Requirements/access-control.md': {'R9', 'R11'}} for every requirement bullet the diff touches."""
    touched: dict[str, set[str]] = {}
    current = ""
    for line in diff.splitlines():
        header = DIFF_FILE.match(line)
        if header:
            current = header.group(1)
            continue
        if not current.startswith("Requirements/") or not current.endswith(".md"):
            continue
        change = DIFF_LINE.match(line)
        if not change:
            continue
        match = _trace.DEFINITION.match(change.group(2))
        if match:
            touched.setdefault(current, set()).add(match.group(1))
    return touched


def traceability(root: Path, family_file: str) -> list[tuple[set[str], str, str]]:
    """(ids, architecture cell, test cell) for every row of that file's ## Traceability table."""
    path = root / family_file
    if not path.is_file():
        return []
    rows = _trace.table_after(path.read_text(encoding="utf-8"), "## Traceability")
    out: list[tuple[set[str], str, str]] = []
    for cells in rows:
        if len(cells) < 3:
            continue
        match = _trace.RANGE.match(cells[0].replace("**", ""))
        if not match:
            continue
        ids = _trace.expand(match.group(1), match.group(2))
        if ids:
            out.append((ids, cells[1], cells[2]))
    return out


def _first_link(cell: str) -> str:
    match = re.search(r"\[([^\]]+)\]", cell)
    return match.group(1) if match else cell.strip()


def report(root: Path, diff: str) -> tuple[str, list[str]]:
    """The markdown comment, and the problems that make the report incomplete."""
    problems: list[str] = []
    touched = changed_ids(diff)
    if not touched:
        return "No requirement bullet changed in this diff.\n", problems

    lines = [
        "## Requirement impact",
        "",
        "| Requirement | Family file | Architecture section | Test family |",
        "|---|---|---|---|",
    ]
    sensitive_hits: list[str] = []
    for family_file in sorted(touched):
        table = traceability(root, family_file)
        if not table:
            problems.append(f"{family_file}: no ## Traceability table, so its requirements resolve to nothing")
        for req in sorted(touched[family_file]):
            arch = tests = ""
            for ids, arch_cell, test_cell in table:
                if req in ids:
                    arch, tests = _first_link(arch_cell), _first_link(test_cell)
                    break
            if not arch:
                problems.append(f"{family_file}: {req} is in no traceability range")
                arch = tests = "**untraced**"
            lines.append(f"| `{req}` | `{family_file}` | {arch} | {tests} |")
            head = re.match(r"^([A-Za-z]+)", req)
            if head and head.group(1) in SENSITIVE:
                sensitive_hits.append(req)

    if sensitive_hits:
        lines += [
            "",
            f"**Read this one closely.** {', '.join(sorted(set(sensitive_hits)))} "
            f"{'belongs' if len(set(sensitive_hits)) == 1 else 'belong'} to the access control, "
            "gateway firewall, identity or operations families: a changed word here changes who "
            "may read or write context data.",
        ]
    lines += ["", "Generated by `scripts/report-pr-impact.py` from the family traceability tables.", ""]
    return "\n".join(lines), problems


def _diff_against(base: str, root: Path) -> str:
    result = subprocess.run(
        ["git", "diff", f"{base}...HEAD", "--", "Requirements/"],
        cwd=root, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        raise SystemExit(f"git diff against {base} failed: {result.stderr.strip()}")
    return result.stdout


def selftest() -> int:
    family = """---
title: Access
---

# Access

## 1. Rules

- **R9** [S] — the gateway MUST narrow a query to the caller's grants.
- **R10** [S] — the gateway MUST refuse an unknown slug.

## Traceability

| Requirement Range | Architecture Section | Test Family |
|---|---|---|
| R9–R10 | [Architecture/05-context-gateway.md#2-pep](../Architecture/05-context-gateway.md#2-pep) | [Testing/01-backend-tests.md#1-unit](../Testing/01-backend-tests.md#1-unit) |
"""
    diff_r9 = """diff --git a/Requirements/access-control.md b/Requirements/access-control.md
--- a/Requirements/access-control.md
+++ b/Requirements/access-control.md
@@ -7,3 +7,3 @@
-- **R9** [S] — the gateway MUST narrow a query to the caller's grants.
+- **R9** [S] — the gateway MUST narrow every query to the caller's grants.
"""
    diff_untraced = diff_r9.replace("**R9**", "**R42**")
    diff_prose = """diff --git a/Requirements/access-control.md b/Requirements/access-control.md
--- a/Requirements/access-control.md
+++ b/Requirements/access-control.md
@@ -3,2 +3,2 @@
-A sentence about the family.
+A different sentence about the family.
"""
    diff_other_folder = diff_r9.replace("Requirements/access-control.md", "Architecture/05-context-gateway.md")

    failures: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "Requirements").mkdir()
        (root / "Requirements" / "access-control.md").write_text(family, encoding="utf-8")

        text, problems = report(root, diff_r9)
        if "| `R9` |" not in text or "05-context-gateway.md#2-pep" not in text or "01-backend-tests.md#1-unit" not in text:
            failures.append(f"a changed R9 did not resolve to its chapter and test family:\n{text}")
        if "Read this one closely" not in text:
            failures.append("a changed access-control requirement raised no warning")
        if problems:
            failures.append(f"a clean corpus reported {problems}")

        text, problems = report(root, diff_untraced)
        if "untraced" not in text or not any("is in no traceability range" in p for p in problems):
            failures.append(f"a requirement outside every range was not reported:\n{text} {problems}")

        text, _ = report(root, diff_prose)
        if "No requirement bullet changed" not in text:
            failures.append(f"a prose-only diff produced a table:\n{text}")

        text, _ = report(root, diff_other_folder)
        if "No requirement bullet changed" not in text:
            failures.append(f"a diff outside Requirements/ produced a table:\n{text}")

        (root / "Requirements" / "access-control.md").write_text(
            family.split("## Traceability")[0], encoding="utf-8"
        )
        text, problems = report(root, diff_r9)
        if not any("no ## Traceability table" in p for p in problems):
            failures.append(f"a family file without a traceability table was not reported: {problems}")

    for failure in failures:
        print(f"FAIL {failure}", file=sys.stderr)
    if failures:
        return 1
    print("ok: a changed requirement resolves to its chapter and test family, a security family "
          "raises a warning, an untraced id and a family without a traceability table are reported, "
          "and prose or another folder produces no table")
    return 0


def main(argv: list[str]) -> int:
    args = argv[1:]
    if args[:1] == ["--selftest"]:
        return selftest()

    diff = ""
    root = Path(".")
    if "--diff-file" in args:
        value = args[args.index("--diff-file") + 1]
        diff = sys.stdin.read() if value == "-" else Path(value).read_text(encoding="utf-8")
        rest = args[args.index("--diff-file") + 2 :]
    elif "--base" in args:
        base = args[args.index("--base") + 1]
        rest = args[args.index("--base") + 2 :]
        root = Path(rest[0]) if rest else Path(".")
        diff = _diff_against(base, root)
        rest = []
    else:
        print(__doc__, file=sys.stderr)
        return 2
    if rest:
        root = Path(rest[0])

    text, problems = report(root, diff)
    sys.stdout.write(text)
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
